name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.31.0
  - pip=23.3.1
  - mlflow=2.21.0
  - hydra-core=1.0.6
  - pip:
      - wandb==0.21.0
      - hydra-joblib-launcher==1.1.2
